#!groovy
// Check properties
properties([disableConcurrentBuilds()])

pipeline {
    agent {
        label 'master'
    }
    stages {
        stage('Preparation') {
            steps {
                    git 'https://github.com/ryzhan/carts.git'
            }
        }
    stage('Build') {
            steps {
                sh 'mvn clean package' 
                
            }
        }
    stage('Test') {
            steps {
                sh 'mvn test' 
                
            }
        }
    stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
            }
    }
    stage('Deploy') {

        environment {
                PRODUCTION_NETWORK_IP = sh(script: 'echo ${PRODUCTION_NETWORK_IP}', , returnStdout: true).trim()
                }

        steps {
            sh "ssh -oStrictHostKeyChecking=no jenkins@$PRODUCTION_NETWORK_IP sudo systemctl stop carts"
            sh "scp /var/lib/jenkins/workspace/JenkinsDemo/target/carts.jar jenkins@$PRODUCTION_NETWORK_IP:~"
            sh "ssh -oStrictHostKeyChecking=no jenkins@$PRODUCTION_NETWORK_IP sudo systemctl start carts"
        }
    }
    }
    post {
        always {
            echo 'I have finished and deleting workspace'
            emailext attachLog: true, body: 'All Done', compressLog: true, subject: 'Deploy', to: 'slavik.ryzhan@gmail.com'
        }
        success {
            echo 'Job succeeeded!'
        }
        unstable {
            echo 'I am unstable :/'
        }
        failure {
            echo 'I failed :('
        }
        changed {
            echo 'Things were different before...'
        }
    }
}
