
- name: Install docker
  gather_facts: No
  hosts: test
  vars:
    user_name: jenkins
  task:
    - name: Install utils
      package:
        name: "{{ item }}"
        state: latest
      become: yes
      with_items:
        - yum-utils
        - lvm2
        - device-mapper-persistent-data

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker/ce.repo
      become: yes

    - name: Install Docker
      package:
        name: docker-ce
        state: latest
        become: yes

    - name: Start Docker service
      service:
        name: docker
        state: starter
        enable: yes
      become: yes

    - name: Add user ansible to docker group
      user:
        name: jenkins
        groups: docker
        append: yes
      become: yes