FROM postgres:12.0
ADD ./init /docker-entrypoint-initdb.d/
ENV MOODLE_DB_USER=moodle_devops/
ENV MOODLE_DB_PASSWORD=1qaz2wsx/
ENV MOODLE_DB_DATABASE=moodle/
ENV POSTGRES_USER=postgres
ENTRYPOINT ["docker-entrypoint.sh"]
EXPOSE 5432