FROM centos:centos7
ENV DB_ROOT_PWD=1qaz2wsx
ENV DB_USER_PWD=1qaz2wsx

RUN yum install https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm -y
RUN yum install postgresql94-server postgresql94-contrib postgresql94-libs postgresql94-devel -y
USER root
RUN /usr/pgsql-9.4/bin/postgresql94-setup initdb
RUN systemctl start postgresql-9.4.service
RUN systemctl enable postgresql-9.4.service
USER postgres
RUN psql -v ON_ERROR_STOP=1 --username postgres <<-EOSQL \n\
    CREATE USER moodle_devops WITH PASSWORD '1qaz2wsx'; \n\
    CREATE DATABASE moodle WITH OWNER moodle_devops ENCODING 'UTF8' LC_COLLATE='en_US.UTF-8' LC_CTYPE='en_US.UTF-8' TEMPLATE=template0; \n\
    EOSQL
RUN sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '192.168.56.20'/" /var/lib/pgsql/9.4/data/postgresql.conf \
RUN echo "host all all 192.168.56.10/32 md5" >> /var/lib/pgsql/9.4/data/pg_hba.conf \
USER root
RUN systemctl restart postgresql-9.4.service
VOLUME  ["/etc/postgresql", "/var/log/postgresql", "/var/lib/postgresql"]
CMD ["/usr/lib/postgresql/9.4/bin/postgres", "-D", "/var/lib/postgresql/9.4/main", "-c", "config_file=/etc/postgresql/9.4/main/postgresql.conf"]
CMD tail -f /dev/null

EXPOSE 5432

/usr/lib/postgresql/9.4/bin/postgres -D /var/lib/postgresql/9.4/main -c config_file=/etc/postgresql/9.4/main/postgresql.conf