---

- name: Install docker and git
  gather_facts: No
  hosts: server_all

  roles:
    - update-centos
    - install-docker
    - install-git
    - install-pip-docker
    
- name: Create and run db docker containers on db-server
  gather_facts: No
  hosts: db

  roles:
    - docker-carts-db
    - docker-catalogue-db
    - docker-user-db

- name: Create docker containers on app-server
  gather_facts: No
  hosts: app
  
  roles:
    - add-docker-network-and-volumes
#    - docker-catalogue
#    - docker-user
#    - docker-carts