---
# tasks file for update-centos

- name: Update OS
  yum:
    name: "*"
    state: latest
  become: yes
  become_user: root
  become_method: sudo

- name: install epel-release
  yum:
    name: epel-release
    state: latest
  become: yes
  become_user: root
  become_method: sudo

- name: Install deltarpm
  yum:
    name: deltarpm
    state: latest
  become: yes
  become_user: root
  become_method: sudo
