- name: Git clone user-db
  git:
    repo: 'https://github.com/ryzhan/user.git'
    dest: /opt/user
    force: yes
  become: yes
  become_user: root
  become_method: sudo

- name: Build image user-db
  docker_image:
    name: user-db
    build:
      path: /opt/user/docker/user-db
      pull: yes
    source: build
  become: yes
  become_user: root
  become_method: sudo

- name: Run user-db container
  docker_container:
    name: user-db
    image: "user-db"
    ports:
      - "27017:27017"
    restart_policy: always
    user: root
  become: yes
  become_user: root
  become_method: sudo
