FROM centos:centos7
ENV DB_ROOT_PWD=1qaz2wsx
ENV DB_USER_PWD=1qaz2wsx

RUN yum install https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm -y
RUN yum install postgresql94-server postgresql94-contrib postgresql94-libs postgresql94-devel -y
USER postgres

RUN    /etc/init.d/postgresql start &&\
    psql --command "CREATE USER moodle_devops WITH SUPERUSER PASSWORD '1qaz2wsx';" &&\
    createdb -O moodle_devops  moodle

RUN echo "host all  all    0.0.0.0/0  md5" >> /etc/postgresql/9.4/main/pg_hba.conf

# And add ``listen_addresses`` to ``/etc/postgresql/9.4/main/postgresql.conf``
RUN echo "listen_addresses='*'" >> /etc/postgresql/9.4/main/postgresql.conf

# Expose the PostgreSQL port
EXPOSE 5432

# Add VOLUMEs to allow backup of config, logs and databases
VOLUME  ["/etc/postgresql", "/var/log/postgresql", "/var/lib/postgresql"]

# Set the default command to run when starting the container
CMD ["/usr/lib/postgresql/9.4/bin/postgres", "-D", "/var/lib/postgresql/9.4/main", "-c", "config_file=/etc/postgresql/9.4/main/postgresql.conf"]

