# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  
  config.vm.define "Postgres_db" do |db|
    db.vm.box = "centos/7"
    db.vm.provider "virtualbox" do |vb|
    vb.name = "Postgres_db7"
    end
    db.vm.network "private_network", ip: "192.168.56.20"
    db.vm.network "forwarded_port", guest: 5432, host: 5432
    db.vm.provision "shell", path: "scenario_db_docker.sh"
  end

  config.vm.define "Lms_moodle" do |web|
    web.vm.box = "centos/7"
    web.vm.provider "virtualbox" do |vb|
    vb.name = "Lms_moodle"
    end
    web.vm.network "private_network", ip: "192.168.56.10"
    web.vm.provision "shell", path: "scenario_lms_moodle.sh"
  end

end


