# We must install pip via apt before we can use the pip module below
- name: Install pip
  yum:
    name: python-pip
    state: latest
  become: yes
  become_user: root
  become_method: sudo

# Install latest version when no specific release is set.
- name: Upgrade latest pip, setuptools, docker-py and docker-compose with pip
  pip:
    name: "{{ item.name }}"
    state: latest
  with_items:
  #  - { name: pip, version: "{{ pip_version_pip }}" }
  #  - { name: setuptools, version: "{{ pip_version_setuptools }}" }
    - { name: docker }
  become: yes
  become_user: root
  become_method: sudo
#  notify: 
#    - Restart docker

